export const restaurants = [
  {
    id: "a757a0e9-03c1-4a2a-b384-8ac21dbe2fb2",
    name: "Dishoom",
    menu: [
      {
        id: "d75f762a-eadd-49be-8918-ed0daa8dd024",
        name: "Chicken tikka masala",
        price: 12,
        ingredients: ["chicken", "rice"],
      },
      {
        id: "c3cb8f92-a2ed-4716-92a1-b6ea813e9049",
        name: "Naan",
        price: 3,
        ingredients: ["bread"],
      },
      {
        id: "bd129641-c0eb-432b-84b6-8b81d2930358",
        name: "Samosa",
        price: 8,
        ingredients: ["chicken", "bread"],
      },
      {
        id: "1a2b3c4d-1111-2222-3333-444455556666",
        name: "Paneer Butter Masala",
        price: 11,
        ingredients: ["paneer", "tomato", "cream", "spices"],
      },
      {
        id: "1a2b3c4d-7777-8888-9999-000011112222",
        name: "Lassi",
        price: 4,
        ingredients: ["yogurt", "sugar", "cardamom"],
      },
      {
        id: "1a2b3c4d-aaaa-bbbb-cccc-ddddeeeeffff",
        name: "Biryani",
        price: 13,
        ingredients: ["rice", "chicken", "spices", "onion"],
      },
      {
        id: "1a2b3c4d-1234-5678-90ab-cdef12345678",
        name: "Aloo Gobi",
        price: 9,
        ingredients: ["potato", "cauliflower", "spices"],
      },
      {
        id: "dishoom-001-unique-uuid",
        name: "Tandoori Chicken",
        price: 14,
        ingredients: ["chicken", "yogurt", "spices", "lemon"],
      },
      {
        id: "dishoom-002-unique-uuid",
        name: "Dal Makhani",
        price: 10,
        ingredients: ["lentils", "cream", "spices", "butter"],
      },
      {
        id: "dishoom-003-unique-uuid",
        name: "Raita",
        price: 4,
        ingredients: ["yogurt", "cucumber", "spices"],
      },
      {
        id: "dishoom-004-unique-uuid",
        name: "Garlic Naan",
        price: 4,
        ingredients: ["bread", "garlic", "butter"],
      },
      {
        id: "dishoom-005-unique-uuid",
        name: "Mango Lassi",
        price: 5,
        ingredients: ["yogurt", "mango", "sugar"],
      },
      {
        id: "dishoom-006-unique-uuid",
        name: "Vegetable Pakora",
        price: 7,
        ingredients: ["vegetables", "chickpea flour", "spices"],
      },
      {
        id: "dishoom-007-unique-uuid",
        name: "Butter Chicken",
        price: 13,
        ingredients: ["chicken", "butter", "tomato", "cream", "spices"],
      },
      {
        id: "dishoom-008-unique-uuid",
        name: "Jeera Rice",
        price: 5,
        ingredients: ["rice", "cumin", "butter"],
      },
      {
        id: "dishoom-009-unique-uuid",
        name: "Masala Chai",
        price: 3,
        ingredients: ["tea", "milk", "spices", "sugar"],
      },
      {
        id: "dishoom-010-unique-uuid",
        name: "Gulab Jamun",
        price: 6,
        ingredients: ["milk", "sugar", "rose water"],
      },
      {
        id: "dishoom-011-unique-uuid",
        name: "Chana Masala",
        price: 8,
        ingredients: ["chickpeas", "tomato", "onion", "spices"],
      },
      {
        id: "dishoom-012-unique-uuid",
        name: "Fish Curry",
        price: 15,
        ingredients: ["fish", "coconut milk", "spices", "tomato"],
      },
      {
        id: "dishoom-013-unique-uuid",
        name: "Bhindi Fry",
        price: 9,
        ingredients: ["okra", "onion", "spices"],
      },
      {
        id: "dishoom-014-unique-uuid",
        name: "Egg Curry",
        price: 10,
        ingredients: ["egg", "tomato", "onion", "spices"],
      },
      {
        id: "dishoom-015-unique-uuid",
        name: "Prawn Masala",
        price: 16,
        ingredients: ["prawn", "tomato", "onion", "spices"],
      },
      {
        id: "dishoom-016-unique-uuid",
        name: "Palak Paneer",
        price: 11,
        ingredients: ["paneer", "spinach", "cream", "spices"],
      },
      {
        id: "dishoom-017-unique-uuid",
        name: "Methi Paratha",
        price: 5,
        ingredients: ["bread", "fenugreek", "spices"],
      },
      {
        id: "dishoom-018-unique-uuid",
        name: "Kheer",
        price: 6,
        ingredients: ["rice", "milk", "sugar", "cardamom"],
      },
      {
        id: "dishoom-019-unique-uuid",
        name: "Onion Bhaji",
        price: 7,
        ingredients: ["onion", "chickpea flour", "spices"],
      },
      {
        id: "dishoom-020-unique-uuid",
        name: "Malai Kofta",
        price: 12,
        ingredients: ["potato", "paneer", "cream", "spices"],
      },
      {
        id: "dishoom-021-unique-uuid",
        name: "Shahi Paneer",
        price: 12,
        ingredients: ["paneer", "cream", "tomato", "spices"],
      },
      {
        id: "dishoom-022-unique-uuid",
        name: "Chicken Korma",
        price: 14,
        ingredients: ["chicken", "cream", "cashew", "spices"],
      },
      {
        id: "dishoom-023-unique-uuid",
        name: "Vegetable Biryani",
        price: 11,
        ingredients: ["rice", "vegetables", "spices"],
      },
      {
        id: "dishoom-024-unique-uuid",
        name: "Lamb Rogan Josh",
        price: 15,
        ingredients: ["lamb", "yogurt", "spices", "tomato"],
      },
      {
        id: "dishoom-025-unique-uuid",
        name: "Paneer Tikka",
        price: 13,
        ingredients: ["paneer", "yogurt", "spices"],
      },
      {
        id: "dishoom-026-unique-uuid",
        name: "Aloo Tikki",
        price: 7,
        ingredients: ["potato", "spices", "bread crumbs"],
      },
      {
        id: "dishoom-027-unique-uuid",
        name: "Chicken Seekh Kebab",
        price: 14,
        ingredients: ["chicken", "spices", "onion"],
      },
      {
        id: "dishoom-028-unique-uuid",
        name: "Baingan Bharta",
        price: 10,
        ingredients: ["eggplant", "tomato", "onion", "spices"],
      },
      {
        id: "dishoom-029-unique-uuid",
        name: "Dhokla",
        price: 6,
        ingredients: ["chickpea flour", "yogurt", "spices"],
      },
      {
        id: "dishoom-030-unique-uuid",
        name: "Moong Dal Halwa",
        price: 8,
        ingredients: ["moong dal", "ghee", "sugar", "cardamom"],
      },
      {
        id: "dishoom-031-unique-uuid",
        name: "Chicken Vindaloo",
        price: 15,
        ingredients: ["chicken", "vinegar", "spices", "potato"],
      },
      {
        id: "dishoom-032-unique-uuid",
        name: "Rajma",
        price: 9,
        ingredients: ["kidney beans", "tomato", "spices"],
      },
      {
        id: "dishoom-033-unique-uuid",
        name: "Pav Bhaji",
        price: 8,
        ingredients: ["vegetables", "potato", "bread", "spices"],
      },
      {
        id: "dishoom-034-unique-uuid",
        name: "Dahi Puri",
        price: 7,
        ingredients: ["puri", "yogurt", "potato", "spices"],
      },
      {
        id: "dishoom-035-unique-uuid",
        name: "Chicken 65",
        price: 13,
        ingredients: ["chicken", "spices", "yogurt"],
      },
      {
        id: "dishoom-036-unique-uuid",
        name: "Paneer Bhurji",
        price: 11,
        ingredients: ["paneer", "onion", "tomato", "spices"],
      },
      {
        id: "dishoom-037-unique-uuid",
        name: "Gajar Halwa",
        price: 8,
        ingredients: ["carrot", "milk", "sugar", "cardamom"],
      },
      {
        id: "dishoom-038-unique-uuid",
        name: "Chicken Chettinad",
        price: 15,
        ingredients: ["chicken", "coconut", "spices"],
      },
      {
        id: "dishoom-039-unique-uuid",
        name: "Pani Puri",
        price: 6,
        ingredients: ["puri", "spiced water", "potato"],
      },
      {
        id: "dishoom-040-unique-uuid",
        name: "Rasgulla",
        price: 7,
        ingredients: ["milk", "sugar", "rose water"],
      },
      {
        id: "dishoom-041-unique-uuid",
        name: "Chicken Do Pyaza",
        price: 14,
        ingredients: ["chicken", "onion", "spices"],
      },
      {
        id: "dishoom-042-unique-uuid",
        name: "Paneer Pasanda",
        price: 13,
        ingredients: ["paneer", "cream", "spices"],
      },
      {
        id: "dishoom-043-unique-uuid",
        name: "Dum Aloo",
        price: 10,
        ingredients: ["potato", "tomato", "spices"],
      },
      {
        id: "dishoom-044-unique-uuid",
        name: "Chicken Handi",
        price: 15,
        ingredients: ["chicken", "cream", "spices"],
      },
      {
        id: "dishoom-045-unique-uuid",
        name: "Kadai Paneer",
        price: 12,
        ingredients: ["paneer", "bell pepper", "spices"],
      },
      {
        id: "dishoom-046-unique-uuid",
        name: "Chicken Bhuna",
        price: 14,
        ingredients: ["chicken", "tomato", "spices"],
      },
      {
        id: "dishoom-047-unique-uuid",
        name: "Moong Dal",
        price: 8,
        ingredients: ["moong dal", "spices", "onion"],
      },
      {
        id: "dishoom-048-unique-uuid",
        name: "Paneer Lababdar",
        price: 13,
        ingredients: ["paneer", "tomato", "cream", "spices"],
      },
      {
        id: "dishoom-049-unique-uuid",
        name: "Chicken Saagwala",
        price: 15,
        ingredients: ["chicken", "spinach", "spices"],
      },
      {
        id: "dishoom-050-unique-uuid",
        name: "Aloo Matar",
        price: 9,
        ingredients: ["potato", "peas", "spices"],
      },
      {
        id: "dishoom-051-unique-uuid",
        name: "Paneer Do Pyaza",
        price: 12,
        ingredients: ["paneer", "onion", "spices"],
      },
      {
        id: "dishoom-052-unique-uuid",
        name: "Chicken Madras",
        price: 15,
        ingredients: ["chicken", "coconut", "spices"],
      },
      {
        id: "dishoom-053-unique-uuid",
        name: "Bhatura",
        price: 5,
        ingredients: ["bread", "yogurt", "flour"],
      },
      {
        id: "dishoom-054-unique-uuid",
        name: "Paneer Malai Tikka",
        price: 13,
        ingredients: ["paneer", "cream", "spices"],
      },
      {
        id: "dishoom-055-unique-uuid",
        name: "Chicken Malai Tikka",
        price: 14,
        ingredients: ["chicken", "cream", "spices"],
      },
      {
        id: "dishoom-056-unique-uuid",
        name: "Aloo Baingan",
        price: 10,
        ingredients: ["potato", "eggplant", "spices"],
      },
      {
        id: "dishoom-057-unique-uuid",
        name: "Paneer Korma",
        price: 12,
        ingredients: ["paneer", "cream", "cashew", "spices"],
      },
      {
        id: "dishoom-058-unique-uuid",
        name: "Chicken Kathi Roll",
        price: 13,
        ingredients: ["chicken", "bread", "spices"],
      },
      {
        id: "dishoom-059-unique-uuid",
        name: "Paneer Kathi Roll",
        price: 12,
        ingredients: ["paneer", "bread", "spices"],
      },
      {
        id: "dishoom-060-unique-uuid",
        name: "Chicken Patiala",
        price: 15,
        ingredients: ["chicken", "egg", "spices"],
      },
      {
        id: "dishoom-061-unique-uuid",
        name: "Paneer Patiala",
        price: 13,
        ingredients: ["paneer", "egg", "spices"],
      },
      {
        id: "dishoom-062-unique-uuid",
        name: "Chicken Kolhapuri",
        price: 15,
        ingredients: ["chicken", "coconut", "spices"],
      },
      {
        id: "dishoom-063-unique-uuid",
        name: "Paneer Kolhapuri",
        price: 13,
        ingredients: ["paneer", "coconut", "spices"],
      },
      {
        id: "dishoom-064-unique-uuid",
        name: "Chicken Xacuti",
        price: 16,
        ingredients: ["chicken", "coconut", "spices"],
      },
      {
        id: "dishoom-065-unique-uuid",
        name: "Paneer Xacuti",
        price: 14,
        ingredients: ["paneer", "coconut", "spices"],
      },
      {
        id: "dishoom-066-unique-uuid",
        name: "Chicken Hyderabadi",
        price: 16,
        ingredients: ["chicken", "yogurt", "spices"],
      },
      {
        id: "dishoom-067-unique-uuid",
        name: "Paneer Hyderabadi",
        price: 14,
        ingredients: ["paneer", "yogurt", "spices"],
      },
      {
        id: "dishoom-068-unique-uuid",
        name: "Chicken Angara",
        price: 15,
        ingredients: ["chicken", "smoked spices"],
      },
      {
        id: "dishoom-069-unique-uuid",
        name: "Paneer Angara",
        price: 13,
        ingredients: ["paneer", "smoked spices"],
      },
      {
        id: "dishoom-070-unique-uuid",
        name: "Chicken Afghani",
        price: 16,
        ingredients: ["chicken", "cream", "spices"],
      },
      {
        id: "dishoom-071-unique-uuid",
        name: "Paneer Afghani",
        price: 14,
        ingredients: ["paneer", "cream", "spices"],
      },
      {
        id: "dishoom-072-unique-uuid",
        name: "Chicken Tikka Roll",
        price: 13,
        ingredients: ["chicken", "bread", "spices"],
      },
      {
        id: "dishoom-073-unique-uuid",
        name: "Paneer Tikka Roll",
        price: 12,
        ingredients: ["paneer", "bread", "spices"],
      },
      {
        id: "dishoom-074-unique-uuid",
        name: "Chicken Frankie",
        price: 13,
        ingredients: ["chicken", "egg", "bread", "spices"],
      },
      {
        id: "dishoom-075-unique-uuid",
        name: "Paneer Frankie",
        price: 12,
        ingredients: ["paneer", "egg", "bread", "spices"],
      },
      {
        id: "dishoom-076-unique-uuid",
        name: "Chicken Bharta",
        price: 14,
        ingredients: ["chicken", "eggplant", "spices"],
      },
      {
        id: "dishoom-077-unique-uuid",
        name: "Paneer Bharta",
        price: 12,
        ingredients: ["paneer", "eggplant", "spices"],
      },
      {
        id: "dishoom-078-unique-uuid",
        name: "Chicken Jalfrezi",
        price: 15,
        ingredients: ["chicken", "bell pepper", "spices"],
      },
      {
        id: "dishoom-079-unique-uuid",
        name: "Paneer Jalfrezi",
        price: 13,
        ingredients: ["paneer", "bell pepper", "spices"],
      },
      {
        id: "dishoom-080-unique-uuid",
        name: "Chicken Dhansak",
        price: 16,
        ingredients: ["chicken", "lentils", "spices"],
      },
    ],
    reviews: [
      {
        id: "5909796d-5030-4e36-adec-68b8f9ec2d96",
        user: "Antony",
        text: "Not bad",
        rating: 5,
      },
      {
        id: "429dea85-11dd-4054-a31e-c60c92e17255",
        user: "Sam",
        text: "No burgers",
        rating: 3,
      },
    ],
  },
  {
    id: "bb8afbec-2fec-491f-93e9-7f13950dd80b",
    name: "Homeslice",
    menu: [
      {
        id: "25402233-0095-49ea-9939-1e67ed89ffb9",
        name: "Margarita",
        price: 9,
        ingredients: ["bread", "cheese", "tomatoes"],
      },
      {
        id: "90902233-0095-49ea-9939-1e67ed89ffb9",
        name: "Chef pizza",
        price: 10,
        ingredients: ["bread", "cheese", "tomatoes", "chicken"],
      },
    ],
    reviews: [
      {
        id: "53b642d7-5e86-4717-a466-0640a1dee076",
        user: "Diana",
        text: "Perfect Margarita",
        rating: 5,
      },
      {
        id: "c27ab88e-375c-4e98-aa94-8a180150a797",
        user: "Sam",
        text: "No burgers again. But Chef Pizza is the best one",
        rating: 4,
      },
      {
        id: "abc0c5e1-cd57-4f0a-99d9-00e6b4533b3a",
        user: "Lolly",
        text: "Good for lunch",
        rating: 5,
      },
    ],
  },
  {
    id: "982bfbce-c5e0-41a0-9f99-d5c20ecee49d",
    name: "Fabrique",
    menu: [
      {
        id: "08c9ffa0-d003-4310-9e15-20978743296e",
        name: "Cinnamon buns",
        price: 5,
        ingredients: ["bread"],
      },
      {
        id: "64a4967c-2080-4a99-9074-4655a4569a95",
        name: "Semlor",
        price: 2,
        ingredients: ["bread", "cream"],
      },
      {
        id: "4bc8528e-26d1-46c3-a522-8e18d10c8c84",
        name: "Saffron bun",
        price: 4,
        ingredients: ["bread"],
      },
    ],
    reviews: [
      {
        id: "53b642d7-5e86-4717-a466-0640a1dee076",
        user: "Agata",
        text: "Best bakery",
        rating: 5,
      },
    ],
  },
  {
    id: "982bfbce-c5e0-41a0-9f99-d5c2gfdse49d",
    name: "No reviews",
    menu: [
      {
        id: "08c9ffa0-d003-4310-9e15-2097asda43296e",
        name: "Cinnamon buns",
        price: 5,
        ingredients: ["bread"],
      },
      {
        id: "64a4967c-2080-4a99-9074-4655vcxzx69a95",
        name: "Semlor",
        price: 2,
        ingredients: ["bread", "cream"],
      },
      {
        id: "4bc8528e-26d1-46c3-a522-8e18d1bcvxzx8c84",
        name: "Saffron bun",
        price: 4,
        ingredients: ["bread"],
      },
    ],
    reviews: [],
  },
  {
    id: "d9241927-09e1-44f3-8986-a76346869037",
    name: "Flat Iron",
    menu: [
      {
        id: "6c02c2ce-b868-4191-b4a7-8686429f4bac",
        name: "Flat Iron Steak",
        price: 10,
        ingredients: ["beef"],
      },
      {
        id: "99bb6fbb-e53b-4b7e-b9c2-23b63b77385d",
        name: "Flat Iron Burger",
        price: 10,
        ingredients: ["bread", "beef"],
      },
    ],
    reviews: [
      {
        id: "5db6247b-ab1c-49db-be1f-8dd27fd38b81",
        user: "Sam",
        text: "Finally! This place is amazing place for breakfast, lunch, dinner and supper",
        rating: 5,
      },
      {
        id: "381b0c31-6360-43ff-80d1-581a116159d8",
        user: "Rebeca",
        text: "Meat here is extremely delicious",
        rating: 5,
      },
    ],
  },
];
